-- SUPER ADMIN (ko'p viloyat)
ALTER TABLE ustalar ADD COLUMN IF NOT EXISTS viloyat VARCHAR(100) DEFAULT 'Toshkent';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS viloyat VARCHAR(100);

CREATE TABLE IF NOT EXISTS adminlar (
  id SERIAL PRIMARY KEY,
  login VARCHAR(50) UNIQUE NOT NULL,
  parol VARCHAR(100) NOT NULL,
  viloyat VARCHAR(100),
  super_admin BOOLEAN NOT NULL DEFAULT false,
  yaratilgan_vaqt TIMESTAMP NOT NULL DEFAULT NOW()
);
INSERT INTO adminlar (login, parol, viloyat, super_admin)
VALUES ('super', 'admin123', NULL, true)
ON CONFLICT (login) DO NOTHING;

-- REYTING VA SHARHLAR
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sharh TEXT;

-- USTA 12 SOAT MAJBURIY FAOLLIK
ALTER TABLE ustalar ADD COLUMN IF NOT EXISTS faol_boshlanish_vaqti TIMESTAMP;
ALTER TABLE ustalar ADD COLUMN IF NOT EXISTS bugun_faol_soniya INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ustalar ADD COLUMN IF NOT EXISTS bugun_off_soni INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ustalar ADD COLUMN IF NOT EXISTS oxirgi_reset_sana DATE;

-- MOYKACHI/PEREGONCHI KM-ASOSLI NARXLASH
ALTER TABLE xizmatlar ADD COLUMN IF NOT EXISTS km_asosli BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE xizmatlar ADD COLUMN IF NOT EXISTS km_narxi NUMERIC(10,2);
UPDATE xizmatlar SET km_asosli = true, km_narxi = 3000 WHERE kod IN ('moyka', 'peregon');
ALTER TABLE orders ADD COLUMN IF NOT EXISTS km NUMERIC(6,2);
